---
- name: Provide Key Share to Generate Root For FSS Vault
  hosts: all
  vars_files:
    - "vars/{{ domain }}/{{ env }}.yml"
  gather_facts: false
  roles:
  - role: vault
  run_once: true
  tags:
  - never
  - generate_root_token
